-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: f82fb149af2c1b552b50e3e38e38ed3a44d4cda1
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        - --max-line-length=120
        - --max-complexity=10
        - --exclude=migrations
    -   id: debug-statements
    -   id: check-json
    -   id: pretty-format-json
